# Generated by Django 4.2.30 on 2026-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('insights', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=list)),
                ('chart_data', models.JSONField(default=dict)),
            ],
        ),
    ]
