# Generated by Django 4.2.30 on 2026-09-16 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashProofSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_text_report', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashproof_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_name', models.CharField(blank=True, default='', help_text='e.g. "Operating Account"', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('last4', models.CharField(blank=True, default='', max_length=10)),
                ('account_type', models.CharField(blank=True, choices=[('checking', 'Checking'), ('payroll', 'Payroll'), ('savings', 'Savings'), ('money_market', 'Money Market'), ('escrow', 'Escrow'), ('other', 'Other')], default='checking', max_length=20)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('mapping_status', models.CharField(blank=True, default='MAPPED', help_text='"MAPPED" or "Account Mapping Required"', max_length=50)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_interbank_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_interbank_payments', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_payments', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accounts', to='cashproof_ai.cashproofsession')),
            ],
            options={
                'ordering': ['bank_name', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='InterbankMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(blank=True, default='', help_text='e.g. IB-001', max_length=20)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('from_bank', models.CharField(blank=True, default='', max_length=255)),
                ('from_account', models.CharField(blank=True, default='', max_length=100)),
                ('to_bank', models.CharField(blank=True, default='', max_length=255)),
                ('to_account', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('debit_description', models.TextField(blank=True, default='')),
                ('credit_description', models.TextField(blank=True, default='')),
                ('match_type', models.CharField(blank=True, default='', max_length=100)),
                ('confidence_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CONFIRMED_INTERBANK', 'Confirmed Interbank'), ('HIGH_PROBABILITY', 'High-Probability Interbank'), ('POSSIBLE_INTERBANK', 'Possible Interbank'), ('POSSIBLE_UNMATCHED', 'Possible / Unmatched — Review Required'), ('AMBIGUOUS', 'Ambiguous — Multiple Candidates')], default='CONFIRMED_INTERBANK', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interbank_matches', to='cashproof_ai.cashproofsession')),
            ],
            options={
                'ordering': ['match_id'],
            },
        ),
        migrations.CreateModel(
            name='ParsedStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cashproof_ai/statements/')),
                ('parse_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client_name_extracted', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name_extracted', models.CharField(blank=True, default='', max_length=255)),
                ('account_number_extracted', models.CharField(blank=True, default='', max_length=100)),
                ('last4_extracted', models.CharField(blank=True, default='', max_length=10)),
                ('account_title_extracted', models.CharField(blank=True, default='', max_length=255)),
                ('account_type_extracted', models.CharField(blank=True, default='', max_length=100)),
                ('currency_extracted', models.CharField(blank=True, default='USD', max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('beginning_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ending_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('statement_total_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('statement_total_debits', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('client_account', models.ForeignKey(blank=True, help_text='Matched ClientAccount; null = not yet mapped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='cashproof_ai.clientaccount')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='cashproof_ai.cashproofsession')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('last4', models.CharField(blank=True, default='', max_length=10)),
                ('account_title', models.CharField(blank=True, default='', max_length=255)),
                ('statement_period', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('check_number', models.CharField(blank=True, default='', max_length=50)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('transaction_type', models.CharField(blank=True, choices=[('A', 'External Deposit'), ('B', 'External Payment'), ('C', 'Interbank / Self-Transfer'), ('D', 'Interest'), ('E', 'Bank Fee / Charge'), ('F', 'Check'), ('G', 'ACH'), ('H', 'Card / Merchant Settlement'), ('I', 'Other')], default='I', max_length=2)),
                ('counterparty_info', models.CharField(blank=True, default='', max_length=500)),
                ('source_file', models.CharField(blank=True, default='', max_length=500)),
                ('source_page', models.CharField(blank=True, default='', max_length=20)),
                ('interbank_status', models.CharField(choices=[('CONFIRMED_INTERBANK', 'Confirmed Interbank'), ('HIGH_PROBABILITY_INTERBANK', 'High-Probability Interbank'), ('POSSIBLE_INTERBANK', 'Possible Interbank'), ('POSSIBLE_UNMATCHED', 'Possible / Unmatched — Review Required'), ('NOT_INTERBANK', 'Not Interbank'), ('EXCLUDED_FEE_INTEREST', 'Excluded — Fee/Interest'), ('EXCLUDED_CUSTOMER_ACH', 'Excluded — Customer ACH'), ('AMBIGUOUS', 'Ambiguous — Multiple Candidates')], default='NOT_INTERBANK', max_length=50)),
                ('interbank_confidence_score', models.IntegerField(blank=True, help_text='0–100 per §6 Step 3', null=True)),
                ('interbank_matched_account', models.CharField(blank=True, default='', max_length=255)),
                ('reason_for_classification', models.TextField(blank=True, default='')),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cashproof_ai.clientaccount')),
                ('interbank_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cashproof_ai.interbankmatch')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashproof_ai.parsedstatement')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
