# Generated by Django 4.2.28 on 2026-08-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Unknown Bank', max_length=100)),
                ('account_number', models.CharField(default='Unknown Account', max_length=50)),
                ('account_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_interbank_deposits', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_interbank_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_deposits', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='StatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='statements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('is_interbank', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='analyzer.bankaccount')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='analyzer.statementupload'),
        ),
    ]
