# Generated by Django 5.2.5 on 2026-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementupload',
            name='source_type',
            field=models.CharField(choices=[('STATEMENT', 'Bank Statement'), ('RECONCILIATION', 'Reconciliation Document')], default='STATEMENT', max_length=20),
        ),
    ]
