# Generated by Django 5.2.5 on 2026-09-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_statementupload_total_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='analyzer.statementupload'),
        ),
    ]
