# Generated by Django 5.2.5 on 2026-10-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_statementupload_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Batch 1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='analyzer.project')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='analyzer.analysisbatch'),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='analyzer.analysisbatch'),
        ),
    ]
