# Generated by Django 4.2.30 on 2026-09-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_generatedreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedReport',
        ),
    ]
