# Generated by Django 4.2.30 on 2026-09-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
