# Generated by Django 4.2.30 on 2026-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_statementupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_title',
            field=models.CharField(blank=True, default='Operating Account', max_length=255, null=True),
        ),
    ]
