# Generated by Django 4.2.30 on 2026-09-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_bankaccount_account_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='interbank_confidence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
