# Generated by Django 4.2.30 on 2026-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_transaction_interbank_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='interbank_match_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
